var searchData=
[
  ['a_0',['a',['../md_README.html#autotoc_md2',1,'CI/CD Pipeline &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml/badge.svg&quot; alt=&quot;CI/CD Pipeline&quot;/&gt;&lt;/a&gt;'],['../md_README.html#autotoc_md3',1,'Code Quality &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml/badge.svg&quot; alt=&quot;Code Quality&quot;/&gt;&lt;/a&gt;']]],
  ['a_20href_20https_3a_20github_20com_20linyea00_20dev_20practice_201_20actions_20workflows_20ci_20cd_20yml_20img_20src_20https_3a_20github_20com_20linyea00_20dev_20practice_201_20actions_20workflows_20ci_20cd_20yml_20badge_20svg_20alt_20ci_20cd_20pipeline_20a_1',['CI/CD Pipeline &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml/badge.svg&quot; alt=&quot;CI/CD Pipeline&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md2',1,'']]],
  ['a_20href_20https_3a_20github_20com_20linyea00_20dev_20practice_201_20actions_20workflows_20code_20quality_20yml_20img_20src_20https_3a_20github_20com_20linyea00_20dev_20practice_201_20actions_20workflows_20code_20quality_20yml_20badge_20svg_20alt_20code_20quality_20a_2',['Code Quality &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml/badge.svg&quot; alt=&quot;Code Quality&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md3',1,'']]],
  ['actions_20workflows_20ci_20cd_20yml_20badge_20svg_20alt_20ci_20cd_20pipeline_20a_3',['CI/CD Pipeline &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml/badge.svg&quot; alt=&quot;CI/CD Pipeline&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md2',1,'']]],
  ['actions_20workflows_20ci_20cd_20yml_20img_20src_20https_3a_20github_20com_20linyea00_20dev_20practice_201_20actions_20workflows_20ci_20cd_20yml_20badge_20svg_20alt_20ci_20cd_20pipeline_20a_4',['CI/CD Pipeline &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml/badge.svg&quot; alt=&quot;CI/CD Pipeline&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md2',1,'']]],
  ['actions_20workflows_20code_20quality_20yml_20badge_20svg_20alt_20code_20quality_20a_5',['Code Quality &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml/badge.svg&quot; alt=&quot;Code Quality&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md3',1,'']]],
  ['actions_20workflows_20code_20quality_20yml_20img_20src_20https_3a_20github_20com_20linyea00_20dev_20practice_201_20actions_20workflows_20code_20quality_20yml_20badge_20svg_20alt_20code_20quality_20a_6',['Code Quality &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml/badge.svg&quot; alt=&quot;Code Quality&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md3',1,'']]],
  ['alt_20ci_20cd_20pipeline_20a_7',['CI/CD Pipeline &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/ci-cd.yml/badge.svg&quot; alt=&quot;CI/CD Pipeline&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md2',1,'']]],
  ['alt_20code_20quality_20a_8',['Code Quality &lt;a href=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml&quot; &gt;&lt;img src=&quot;https://github.com/linyea00/dev-practice-1/actions/workflows/code-quality.yml/badge.svg&quot; alt=&quot;Code Quality&quot;/&gt;&lt;/a&gt;',['../md_README.html#autotoc_md3',1,'']]],
  ['autónomos_9',['DevSecOps en Sistemas Autónomos',['../md_README.html',1,'']]]
];
